name: "Setup project"
runs:
  using: "composite"
  steps:

  ################################################################################
  # Base dependencies
  ################################################################################

  - if: runner.os == 'macOS'
    run: brew install age swift-format scdoc
    shell: bash
  - if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install -y scdoc age
    shell: bash
  - if: runner.os == 'Windows'
    run: choco install age.portable
    shell: pwsh


  ################################################################################
  # Swift
  ################################################################################

  # Install an SDK so we can package a static Linux binary
  # See https://www.swift.org/install/macos/ (under 'Older releases'), 
  # and use the 'Copy install command' to get the correct command.
  # Also installing the Swift toolchain itself on macOS to ensure compatibility with the SDK.
  - if: runner.os == 'macOS' && matrix.os == 'macos-26'
    run: |
      curl -L -s -o swift.pkg https://download.swift.org/swift-6.2.3-release/xcode/swift-6.2.3-RELEASE/swift-6.2.3-RELEASE-osx.pkg
      sudo installer -pkg swift.pkg -verbose -dumplog -target /
      env TOOLCHAINS=swift swift sdk install https://download.swift.org/swift-6.2.3-release/static-sdk/swift-6.2.3-RELEASE/swift-6.2.3-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum f30ec724d824ef43b5546e02ca06a8682dafab4b26a99fbb0e858c347e507a2c
    shell: bash
  
  - if: runner.os == 'Linux'
    run: |
      case "${{ runner.arch }}" in
        X64) arch= ;;
        ARM64) arch=-aarch64 ;;
        *) echo "unknown architecture: ${{ runner.arch }}"; exit -1 ;;
      esac
      curl -L -s https://download.swift.org/swift-6.2.3-release/ubuntu2204$arch/swift-6.2.3-RELEASE/swift-6.2.3-RELEASE-ubuntu22.04$arch.tar.gz | tar xvz 
      echo "$GITHUB_WORKSPACE/swift-6.2.3-RELEASE-ubuntu22.04$arch/usr/bin" >> $GITHUB_PATH
    shell: bash

  - if: runner.os == 'Windows'
    uses: compnerd/gha-setup-swift@main
    with:
      branch: swift-6.2.3-release
      tag: 6.2.3-RELEASE
