name: "Setup project"
runs:
  using: "composite"
  steps:

  ################################################################################
  # Base dependencies
  ################################################################################

  - if: runner.os == 'macOS'
    run: brew install age swift-format scdoc
    shell: bash
  - if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install -y scdoc
      # Age on current Ubuntu doesn't support plugins
      # sudo apt-get install age
      case "${{ runner.arch }}" in
        X64) arch=amd64 ;;
        ARM64) arch=arm64 ;;
        *) echo "unknown architecture: ${{ runner.arch }}"; exit -1 ;;
      esac
      curl -L -s https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-$arch.tar.gz  | tar xvz
      echo "$GITHUB_WORKSPACE/age" >> $GITHUB_PATH
    shell: bash
  - if: runner.os == 'Windows'
    run: choco install age.portable
    shell: pwsh


  ################################################################################
  # Swift
  ################################################################################

  # - if: runner.os == 'macOS'
  #   run: |
  #     curl -L -s -o swift.pkg https://download.swift.org/swift-5.9.2-release/xcode/swift-5.9.2-RELEASE/swift-5.9.2-RELEASE-osx.pkg
  #     # sudo installer -pkg swift.pkg -verbose -dumplog -target /
  #     tar xvf swift.pkg 
  #     tar xvf swift-5.9.2-RELEASE-osx-package.pkg/Payload
  #     echo "$GITHUB_WORKSPACE/usr/bin" >> $GITHUB_PATH
  #   shell: bash

  # Install a 6.0 toolchain and SDK so we can package a static Linux binary
  # Used by setting TOOLCHAINS=swift in the environment
  # Once the macOS runner has a Swift 6 compiler, we can remove the toolchain download.
  - if: runner.os == 'macOS'
    run: |
      curl -L -s -o swift.pkg https://download.swift.org/swift-6.0-branch/xcode/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-09-17-a/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-09-17-a-osx.pkg
      sudo installer -pkg swift.pkg -verbose -dumplog -target /
      env TOOLCHAINS=swift swift sdk install https://download.swift.org/swift-6.0-branch/static-sdk/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-09-17-a/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-09-17-a_static-linux-0.0.1.artifactbundle.tar.gz --checksum 83a88650cd0675552ce2cf8159c31966fde73418f49493c1644073fffe8be9f4

    shell: bash
  
  - if: runner.os == 'Linux'
    run: |
      case "${{ runner.arch }}" in
        X64) arch= ;;
        ARM64) arch=-aarch64 ;;
        *) echo "unknown architecture: ${{ runner.arch }}"; exit -1 ;;
      esac
      curl -L -s https://download.swift.org/swift-5.9.2-release/ubuntu2204$arch/swift-5.9.2-RELEASE/swift-5.9.2-RELEASE-ubuntu22.04$arch.tar.gz | tar xvz 
      echo "$GITHUB_WORKSPACE/swift-5.9.2-RELEASE-ubuntu22.04$arch/usr/bin" >> $GITHUB_PATH
    shell: bash

  - if: runner.os == 'Windows'
    uses: compnerd/gha-setup-swift@main
    with:
      branch: swift-5.9.2-release
      tag: 5.9.2-RELEASE
